model:
  name: huawei-noah/TinyBERT_General_4L_312D
  pooler: mean
fabric:
  accelerator: cuda
  devices: 8
  precision: bf16-mixed
  strategy: deepspeed_stage_1
s3bucket: embedding-dataset-clean
dataset:
  sampling_rates:
    amazon_qa: 10
    gooaq: 10
    msmarco: 20
    stack_exchange_title_body: 0.5
    wiki_answers: 0.1
    paq: 0.5
    s2orc: 3
    yahoo_answers: 20
    reddit: 0.2
    esci: 10
  max_batches: 14648
dataloader:
  batch_size: 1024
  pin_memory: true
  num_workers: 0
tokenizer_options:
  padding: true
  truncation: true
  return_tensors: pt
  max_length: 128
hyper_parameters:
  loss: InfoNCELoss
  optimizer: AdamW
  optimizer_options:
    lr: 0.00005
    betas:
    - 0.9
    - 0.999
    eps: 1.0e-08
    weight_decay: 0.01
    amsgrad: false
  epochs: 1
callbacks:
    - name: MTEBEvaluationCallback
      options:
        tasks: [STS12, STS13, STS14, STS15, STS16, STS17, SciFact, TRECCOVID, QuoraRetrieval]
        task_langs: [en]
        steps: 5000
    - name: WandBLogger
      options:
        metrics_logger_step: batch
    - name: ModelCheckpointCallback
      options:
        num_batches: 5000
scheduler:
  turn_on: true
  warmup_min_lr: false
  warmup_num_steps: 500