name: CD

on:
  push:
    tags:
      - 'v*'

env:
  HOST: ${{ secrets.FINETUNER_HOST }}
  JINA_AUTH_TOKEN: ${{ secrets.JINA_AUTH_TOKEN }}

jobs:

  update-docs:
    name: Update docs
    runs-on: ubuntu-latest
    steps:
      - uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: Manual Docs Build
          token: ${{ secrets.JINA_DEV_BOT }}
          inputs: '{ "release_token": "${{ env.release_token }}", "triggered_by": "TAG"}'
        env:
          release_token: ${{ secrets.FINETUNER_RELEASE_TOKEN }}

  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Release to PyPI
        env:
          TWINE_USERNAME: ${{ secrets.TWINE_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}
          JINA_SLACK_WEBHOOK: ${{ secrets.JINA_SLACK_WEBHOOK }}
        run: |
          pip install twine wheel
          python setup.py sdist
          twine upload dist/*
