name: CI

on: [push]

env:
  HOST: http://18:192:5:194

jobs:
  style-lint-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install requirements
        run: make init
      - name: Lint with flake8, black and isort
        run: make style
      - name: Run tests
        run: make test
