name: CI

on: [push]

env:
  HOST: ${{ secrets.FINETUNER_HOST }}
  JINA_AUTH_TOKEN: ${{ secrets.JINA_AUTH_TOKEN }}

jobs:

  check-codestyle:
    name: Check codestyle
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install requirements
        run: make init
      - name: Lint with flake8, black and isort
        run: make style

  run-tests:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install requirements
        run: make init
      - name: Run tests
        run: make test

  # just for blocking the merge until all parallel core-test are successful
  success-all-test:
    needs: run-tests
    if: always()
    runs-on: ubuntu-latest
    steps:
      - uses: technote-space/workflow-conclusion-action@v2
      - name: Check Failure
        if: env.WORKFLOW_CONCLUSION == 'failure'
        run: exit 1
      - name: Success
        if: ${{ success() }}
        run: echo "All Done"